pull request
NescafeByBolyukh/homework2 pull request #2
Opened 2019-11-08 15:04 UTC by NescafeByBolyukh

2019-11-08 17:45 UTC, karmeljuk requested changes
Do minor css changes

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +    margin: 6px 0 12px 0;
optimize margin

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +    background-color: #ffff66;
optimize color

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +    margin: 10px 0 10px 0;
optimize margin

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +        margin-bottom: 0.4%;
.4%

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +        margin-left: 0.4%;
.4%

2019-11-08 17:45 UTC, karmeljuk commented on css/style.css
> +        margin-left: 0.5%
.5%

2019-11-08 18:12 UTC, NescafeByBolyukh commented
Done optimization of margins and bgcolor.

2019-11-11 11:36 UTC, karmeljuk approved these changes

2019-11-11 11:36 UTC, karmeljuk commented
code ok

2019-11-11 11:37 UTC, merged